#!/usr/bin/env bash
#Installing ENgine X
#sudo apt-get update
#sudo apt-get -y install nginx
#echo 'holberton school' | sudo tee /var/www/html/index.html
#sudo service nginx start
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
